name: Kubernetes
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
baseurl: /
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: "v1.1"
    values:
      version: "v1.1"
      versionfilesafe: "v1_1"
      layout: docwithnav
      showedit: true
      githubbranch: "release-1.1"
permalink: pretty