name: Kubernetes
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
baseurl: /
incremental: true

safe: false
lsi: false

defaults:
  -
    scope:
      path: "docs"
    values:
      version: "v1.2"
      layout: docwithnav
      showedit: true
      githubbranch: "release-1.2"
      docsbranch: "master"
permalink: pretty
