name: Kubernetes
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  use_coderay: true
baseurl: /

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docwithnav"
  -
    scope:
      path: "v1.2"
    values:
      version: "v1.2"
      versionfilesafe: "v1_1"

permalink: pretty