name: Kubernetes
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  enable_coderay: true
baseurl: /
destination: ../kubernetes.github.io-built/

safe: false
lsi: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docwithnav"
  -
    scope:
      path: "v1.1"
    values:
      version: "v1.1"
      versionfilesafe: "v1_1"
      showedit: true
permalink: pretty